apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: zayamadeel/scd-project-frontend
          ports:
            - containerPort: 3001
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://backend-service:3000"
          volumeMounts:
            - name: frontend-code
              mountPath: /app
      volumes:
        - name: frontend-code
          hostPath:
            path: /home/user/project/frontend
