name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        eval $(minikube docker-env)

    - name: Build frontend image
      run: docker build -t frontend:latest .

    - name: Build backend image
      run: docker build -t backend:latest ./backend

    - name: Build nginx image
      run: docker build -t nginx:latest ./nginx

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push images to Docker Hub
      run: |
        docker tag frontend:latest ${{ secrets.DOCKER_USERNAME }}/frontend:latest
        docker tag backend:latest ${{ secrets.DOCKER_USERNAME }}/backend:latest
        docker tag nginx:latest ${{ secrets.DOCKER_USERNAME }}/nginx:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/nginx:latest

    - name: Create Namespace (if not exists)
      run: |
        kubectl create namespace my-app-namespace --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to Minikube
      run: |
        kubectl apply -n my-app-namespace -f kubernetes/
